user_input = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""

lines = user_input.splitlines()
grid = []
for line in lines:
    line = list(line)
    grid.append(line)
start = grid[0].index("S")
S_position = grid[0][start]

for i in range(len(grid)):
    for j in range(len(line)):
        down = [i-1][]
        if down print(grid[0][j])